// noinspection GroovyAssignabilityCheck
pipeline {
    // 指定运行此流水线的节点
    agent {
        docker {
            image 'maven:3.6.2-jdk-8'
            args '-v /root/.m2:/root/.m2'
        }
    }

    // 流水线的各个阶段
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deploy') {
            steps {
                // 通过 ssh 将项目文件发送到执行的服务器上（Local WSL 是在 Jenkins 管理界面中配置的服务器信息）
                sshPublisher(publishers: [sshPublisherDesc(configName: 'Local WSL', transfers: [sshTransfer(cleanRemote: false, excludes: '', execCommand: 'docker --version', execTimeout: 120000, flatten: false, makeEmptyDirs: false, noDefaultExcludes: false, patternSeparator: '[, ]+', remoteDirectory: '/jenkins-practice', remoteDirectorySDF: false, removePrefix: 'jenkins-practice/target', sourceFiles: 'jenkins-practice/target/jenkins-practice.jar')], usePromotionTimestamp: false, useWorkspaceInPromotion: false, verbose: false)])
            }
        }
    }

    post {
        always{
            script{
                println("流水线结束后，经常做的事情")
            }
        }

        success{
            script{
                println("流水线成功后，要做的事情")
            }

        }
        failure{
            script{
                println("流水线失败后，要做的事情")
            }
        }

        aborted{
            script{
                println("流水线取消后，要做的事情")
            }

        }
    }
}